# Per favore, consulta la documentazione per tutte le opzioni di configurazione:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Mantieni le dipendenze di Composer (PHP) aggiornate
  - package-ecosystem: "composer"
    directory: "/" # La directory dove si trova il file composer.json
    schedule:
      interval: "daily" # Controlla gli aggiornamenti ogni giorno
    labels:
      - "dependencies"
      - "php"

  # Mantieni le dipendenze di npm (JavaScript) aggiornate, se presenti
  - package-ecosystem: "npm"
    directory: "/" # La directory dove si trova il file package.json
    schedule:
      interval: "daily" # Controlla gli aggiornamenti ogni giorno
    labels:
      - "dependencies"
      - "javascript"

  # Mantieni le GitHub Actions aggiornate, se presenti
  - package-ecosystem: "github-actions"
    directory: "/" # La directory dove si trovano i workflow di GitHub Actions (.github/workflows/)
    schedule:
      interval: "weekly" # Controlla gli aggiornamenti ogni settimana
    labels:
      - "dependencies"
      - "github-actions"
